Fix: Fix a PHP fatal error caused when saving a custom post type slug for the `Unit Preview` option
Error:
```
Fatal error: Uncaught Error: Call to undefined method AmazonAutoLinks_PostType_UnitPreview::_replyToRegisterCustomPreviewPostType() in ...amazon-auto-links/include/core/main/admin/setting/general/AmazonAutoLinks_AdminPage_Setting_General_UnitPreview.php on line 154
```