Fix: Fix a bug that causes a PHP fatal error
Fatal error: Uncaught TypeError: Argument 3 passed to AmazonAutoLinks_ScraperDOM_Product::___removeTags() must be an instance of DOMNode, null given, called in ...AmazonAutoLinks_ScraperDOM_Product.php on line 342.

This occurs when the content element is not fund with XPath.